### ISSUE TITLE
Carrier Username and Pass Auth is not working

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#98]
The username/password is not being sent to the carrier.  The PBX username/password is being sent

**Comment by mackhendricks** [comment]
It's currently in the Master branch, but will be formally wrapped into the 0.52 release

**Comment by mackhendricks** [comment]
Fixed in 0.52

**Comment by tiefighter** [comment]
Maybe It's not fixed yet on 0.5221
I got error on creating carrier with user/pass method. IP based auth is working perfectly.

This is dsiprouter.log:
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: INSERT INTO dr_gw_lists (gwlist, description) VALUES (%s, %s)
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: INSERT INTO dr_gw_lists (gwlist, description) VALUES (%s, %s)
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ('', 'name:CARRIER1')
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ('', 'name:CARRIER1')
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ROLLBACK
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ROLLBACK
7:34] [DEBUG] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py->672]: Connection <_mysql.connection open to 'localhost' at 0x7f0b3003ed48> being returned to pool
7:34] [DEBUG] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py->672]: Connection <_mysql.connection open to 'localhost' at 0x7f0b3003ed48> being returned to pool
7:34] [DEBUG] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py->862]: Connection <_mysql.connection open to 'localhost' at 0x7f0b3003ed48> rollback-on-return
7:34] [DEBUG] [/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py->862]: Connection <_mysql.connection open to 'localhost' at 0x7f0b3003ed48> rollback-on-return
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->122]: 177.19.xxx.xx - - [02/Aug/2019 16:57:34] "POST /carriergroups HTTP/1.1" 500 -
7:34] [INFO] [/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->122]: 177.19.xxx.xx - - [02/Aug/2019 16:57:34] "POST /carriergroups HTTP/1.1" 500 -

On webinterface I got:
Server Issue
Detailed Information:
Please check your configuration and try the request again!
Check out the dSIPRouter Github page for more information about the platform.
To submit a bug for review go to the dSIPRouter Issues page and submit a new issue with a detailed explanation and screenshots of the issue.
